### PR TITLE
Set Jekyll up for blogging

### PR DESCRIPTION
**Pull request by jmdeldin**
## What

I converted your site into the Jekyll blog layout, so you can actually use markdown (just create a post in `_posts/YYYY-MM-DD-title.md`).

## Testing

Locally:

```sh
gem install github-pages
rake server
```

:cake:

### CODE REVIEW

**Comment by jmdeldin** [comment]
pizza-spin

**Comment by jmdeldin** [comment]
running-over

**Comment by ckuttruff** [comment]
lol, so terrible.  Fine, you've convinced me

**Comment by ckuttruff** [comment]
Also, you're aces :)
<3

**Comment by jmdeldin** [comment]
icecream_kid

Yay!

**Pull request merged**
